services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: rails_app_web
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-app
    command: rails s -b 0.0.0.0