# Base Image
FROM ruby:3.4.4

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set the working directory
WORKDIR /rails-app

COPY . .
RUN bundle install

RUN rails assets:precompile